imports:
    # Framework configurations
    - { resource: parameters.yml }
    - { resource: security/ }

    # Bundle configurations
    - { resource: bundle/ }
    - { resource: "@DataNormalizerBundle/Resources/config/commands.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
parameters:
    locale: en