#
# Configuration index
#
imports:
    # Framework configurations
    - { resource: parameters.yml }
    - { resource: security/ }

    # Bundle configurations
    - { resource: bundle/ }

    # Data normalizer dependency injections
    - { resource: "@DataNormalizerBundle/Resources/config/commands.yml" }
    - { resource: "@DataNormalizerBundle/Resources/config/services.yml" }

#
# Put parameters here that don't need to change
# on each machine where the app is deployed
#
parameters:
    locale: en