#
# Keyword Storage Services
#
services:
  #
  # Keywords manager
  #
  keyword_storage.manage_keywords_use_case:
    class: KeyworStorageBundle\Services\ManageKeyword
    arguments:
      - "@keyword_storage.keyword_repository"

  #
  # Keywords repository
  #
  keyword_storage.keyword_repository:
    class: KeyworStorageBundle\Infrastructure\DoctrineKeywordRepository
    factory:
      - "@doctrine.orm.default_entity_manager"
      - "getRepository"
    arguments:
      - "KeywordStorageBundle:keyword"

