#
# Keyword Storage Services
#
services:
  #
  # Keywords manager
  #
  keyword_storage.create_keywords_use_case:
    class: KeywordStorageBundle\Services\CreateKeywords
    arguments:
      - "@keyword_storage.keyword_repository"

  keyword_storage.modify_keywords_use_case:
    class: KeywordStorageBundle\Services\ModifyKeywords
    arguments:
      - "@keyword_storage.keyword_repository"

  keyword_storage.get_keywords_use_case:
    class: KeywordStorageBundle\Services\GetKeywords
    arguments:
      - "@keyword_storage.keyword_repository"

  #
  # Keywords repository
  #
  keyword_storage.keyword_repository:
    class: KeywordStorageBundle\Infrastructure\DoctrineKeywordRepository
    factory:
      - "@doctrine.orm.default_entity_manager"
      - "getRepository"
    arguments:
      - "KeywordStorageBundle:Keyword"

