services:
    #
    # Data normalizer consumer
    #
    app.command.twitter_consumer_command:
        class: DataNormalizer\Infrastructure\Bundle\Command\TwitterConsumerCommand
        arguments:
          - "@rs_queue.consumer"
          - "@data_normalizer.sqs.enqueue"
        tags:
            - { name: console.command }

    app.command.instagram_consumer_command:
        class: DataNormalizer\Infrastructure\Bundle\Command\InstagramConsumerCommand
        arguments:
          - "@rs_queue.consumer"
          - "@data_normalizer.sqs.enqueue"
        tags:
            - { name: console.command }