KeywordStorage\Domain\Model\Keyword:
  type: entity
  repositoryClass: KeywordStorage\Infrastructure\Repository\DoctrineKeywordRepository
  table: keywords
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 100
      unique: true
    lastFetch:
      type: datetime
      column: last_fetch
      nullable: true