#
# Keyword Storage Services
#
services:
  #
  # Keywords manager
  #
  keyword_storage.create_keywords_use_case:
    class: KeywordStorage\Application\CreateKeywords
    arguments:
      - "@keyword_storage.keyword_repository"

  keyword_storage.modify_keywords_use_case:
    class: KeywordStorage\Application\ModifyKeywords
    arguments:
      - "@keyword_storage.keyword_repository"

  keyword_storage.get_keywords_use_case:
    class: KeywordStorage\Application\GetKeywords
    arguments:
      - "@keyword_storage.keyword_repository"

  #
  # Keywords repository
  #
  keyword_storage.keyword_repository:
    class: KeywordStorage\Infrastructure\Repository\DoctrineKeywordRepository
    factory:
      - "@doctrine.orm.default_entity_manager"
      - "getRepository"
    arguments:
      - "Bundle:Keyword"

