#
# Mineur configurations
#

# Twitter Stream Api
twitter_stream_api_client:
    twitter:
        consumer_key: '%twitter_stream_consumer_key%'
        consumer_secret: '%twitter_stream_consumer_secret%'
        access_token: '%twitter_stream_access_token%'
        access_token_secret: '%twitter_stream_access_token_secret%'

# Instagram Parser
instagram_parser:
    query_id: '%instagram_parser_query_id%'