# RS Queue
rs_queue:
    queues:
        tweets: "queues:tweets"
        instagram_posts: "queues:instagram_posts"
        # another queue...
    serializer: ~
    server:
        redis:
            host: 127.0.0.1
            port: 6379
            database: ~